### ISSUE TITLE
전역 스타일을 설정해야될 것 같음

### ISSUE THREAD

**Issue by tkddn204** [gong-clone/programmers-clone#24]
body 스타일을 적용해야 `rem` 단위가 프로그래머스 사이트랑 동일하게 되는 것을 발견했습니다
따라서 전역스타일 설정을 따로 해놓는게 좋을 것 같습니다
`Application` 디렉터리에 `GlobalStyle.ts` 파일을 하나 만들어서 관리하는 것을 제안합니다

**Comment by yg1110** [comment]
전역스타일 필요한 것에 동의합니다.
box-sizing: border-box; 등을 설정할때도 쓸 수 있을거 같습니다.

**Comment by HyeanWoo** [comment]
저도 동의합니다

**Comment by tkddn204** [comment]
normalize 참고 링크 올려드립니다
https://github.com/necolas/normalize.css/blob/master/normalize.css

**Comment by HyeanWoo** [comment]
전역스타일에 `.root-index`에 해당하는 요소인 `overflow-x: hidden;`을 추가하면 어떨까요?
찾아보니까 `.root-index`는 body에서만 쓰이고 다른데서는 쓰이지않기 때문에 괜찮은것 같습니다.

**Comment by HyeanWoo** [comment]
그리고 `:root`부분은 나중에 어떤식으로 추가되는지 알고 싶습니다!

**Comment by tkddn204** [comment]
> 전역스타일에 `.root-index`에 해당하는 요소인 `overflow-x: hidden;`을 추가하면 어떨까요?
> 찾아보니까 `.root-index`는 body에서만 쓰이고 다른데서는 쓰이지않기 때문에 괜찮은것 같습니다.


네 `globalStyle`의 `body`에 `overflow-x: hidden;`를 추가하면 될 것 같습니다.
이슈 열어서 추가 부탁드립니다.

**Comment by tkddn204** [comment]
> 그리고 `:root`부분은 나중에 어떤식으로 추가되는지 알고 싶습니다!

`:root` 부분은 현재 테마로 관리하고 있습니다.
"나중에 어떤식으로 추가된다"의 의미를 잘 이해하지 못했는데, 추가 설명 부탁드립니다.

**Comment by HyeanWoo** [comment]
테마로 관리되는 부분을 제가 깜빡했네요. `globalStyle`부분만 이슈열어서 추가하겠습니다.
