### ISSUE TITLE
뱃지 폴더이름 에러

### ISSUE THREAD

**Issue by yg1110** [gong-clone/programmers-clone#41]
뱃지 폴더를 import 했을 때의 경로는
import ItemBadgeLabel from './SwiperSlide/ItemWrap/ItemBadgeState/ItemBadgeLabel' 되어있습니다.
하지만 pull받았을 때 폴더명은
SwiperSlide/ItemWrap/itemBadgeState/
되어있어서 경로를 찾을수 없다고 뜹니다.

그래서 폴더명을 itemBadgeState -> ItemBadgeState로 바꾸면 에러는 사라지지만,
같은 폴더명으로 인식하여 git status에는 바뀐파일이 없다고 뜹니다.

아예 따른 폴더명을 바꿔서 올려야 할 것같습니다
액션에서 에러나는것도 이것 때문이 아닐지?

**Comment by tkddn204** [comment]
아 디렉토리 앞글자가 대문자가 아니어서 그런 것 같습니다
이 [스택오버플로우 답변](https://stackoverflow.com/a/30373505)에 따르면
컴포넌트 이름이 소문자로 시작할 경우 html 태그로 인식해서 찾는다고합니다
모든 컴포넌트용 디렉터리들의 맨 앞 글자를 대문자로 변경하면 될 것 같습니다
수정해서 PR 부탁드립니다

**Comment by tkddn204** [comment]
git에서 디렉터리명 변경은 [이 스택오버플로우 답변](https://stackoverflow.com/a/11183844)을 참고하셔도 될 것 같습니다

**Comment by yg1110** [comment]
디렉토리를 이동시켜서 폴더명을 바꾸는군요
감사합니다 👍 
다음커밋에서 같이 올릴게요

**Comment by tkddn204** [comment]
이 버그가 난 이후로 머지할 때 다 오류가 나는군요
따로 빠르게 hotfix로 고치는게 좋겠습니다

**Comment by yg1110** [comment]
아 그렇군여 지금까지 한거 바로올리겠습니다
